# Generated by Django 4.0.5 on 2022-06-17 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('event_description', models.TextField(blank=True, max_length=500)),
                ('event_venue', models.CharField(max_length=100)),
                ('event_date', models.CharField(max_length=100)),
                ('event_time', models.TimeField(auto_now_add=True)),
                ('event_image', models.ImageField(default='media/default.svg', upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.category')),
            ],
        ),
    ]
