# Generated by Django 4.0.5 on 2022-06-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_price',
            field=models.IntegerField(default=0),
        ),
    ]
