# Generated by Django 4.0.5 on 2022-06-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
